### ISSUE TITLE
Error: Couldn't find a result file

### ISSUE THREAD

**Issue by FinnFrotscher** [inlife/nexrender#342]
I am getting this error when rendering. Any idea of the origin?
I am on the newest version of both globally installed cli and node modules.

```
[qDuniGSE9KlcUlTEe09Gs] rendering job...
[qDuniGSE9KlcUlTEe09Gs] rendering took ~12.336 sec.
[qDuniGSE9KlcUlTEe09Gs] writing aerender job log to: /Users/finnfrotscher/code/cofenster/api.renderer/tmp/aerender-qDuniGSE9KlcUlTEe09Gs.log
[qDuniGSE9KlcUlTEe09Gs] dumping aerender log:
Running Script: /Users/finnfrotscher/code/cofenster/api.renderer/tmp/qDuniGSE9KlcUlTEe09Gs/nexrender-qDuniGSE9KlcUlTEe09Gs-script.jsx
WARNING:After Effects warning: timeSpanStart of -0,87 seconds will cause render to have frames outside of range defined by comp displayStartTime (0,87) and end of comp duration (26,63). Render will succeed, but may have blank frames.
aerender version 17.0.5x16
PROGRESS: Launching After Effects...
PROGRESS: ...After Effects successfully launched


[ERROR]

{}
lifecycle error Error: Couldn't find a result file
    at ChildProcess.<anonymous> (/Users/finnfrotscher/code/cofenster/api.renderer/node_modules/@nexrender/core/src/tasks/render.js:137:31)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
tick 13:28:47
```

**Comment by FinnFrotscher** [comment]
i added this snipped to `core/tasks/render.js`
```
  instance.on('close', (code) => {
      settings.logger.log(`[${job.uid}] ${code}`)
```
ae finishes with code 0.
```
[Nk2ywSqwKfcDcvrz7n7i-] rendering job...
[Nk2ywSqwKfcDcvrz7n7i-] spawning aerender process: /Applications/Adobe After Effects 2020/aerender -project /Users/finnfrotscher/code/cofenster/api.renderer/tmp/Nk2ywSqwKfcDcvrz7n7i-/template.aet -comp main -output /Users/finnfrotscher/code/cofenster/api.renderer/tmp/Nk2ywSqwKfcDcvrz7n7i-/result.mov -s 0 -r /Users/finnfrotscher/code/cofenster/api.renderer/tmp/Nk2ywSqwKfcDcvrz7n7i-/nexrender-Nk2ywSqwKfcDcvrz7n7i--script.jsx
[Nk2ywSqwKfcDcvrz7n7i-] 0
```

but  
`-output /Users/finnfrotscher/code/cofenster/api.renderer/tmp/Nk2ywSqwKfcDcvrz7n7i-/result.mov` 
is empty

**Comment by FinnFrotscher** [comment]
```

$ cat run.sh                         
#!/bin/bash
/Applications/Adobe\ After\ Effects\ 2020/aerender \
    -project /Users/finnfrotscher/code/cofenster/api.renderer/tmp/cUpuOGWAJ9WFoeZb8PivP/template.aet \
    -comp main \
    -output /Users/finnfrotscher/code/cofenster/api.renderer/tmp/cUpuOGWAJ9WFoeZb8PivP/result.mov \
    -s 0 \
    -r /Users/finnfrotscher/code/cofenster/api.renderer/tmp/cUpuOGWAJ9WFoeZb8PivP/nexrender-cUpuOGWAJ9WFoeZb8PivP-script.jsx


$sudo bash run.sh                                  
aerender version 17.0.5x16
PROGRESS: Launching After Effects...
PROGRESS: ...After Effects successfully launched
Running Script: /Users/finnfrotscher/code/cofenster/api.renderer/tmp/cUpuOGWAJ9WFoeZb8PivP/nexrender-cUpuOGWAJ9WFoeZb8PivP-script.jsx

$ 

```

**Comment by inlife** [comment]
Seems like aerender doesn't like something that goes inside of the aep project.
And it renders just fine if you use GUI for that, correct?

**Comment by FinnFrotscher** [comment]
I opened the template and ran the script from the vscode devtools. no issues. I have not tried actually rendering the project from the gui. will do an report back.

**Comment by phlexib** [comment]
I had a similar error message. It appears that in my AE project, the default Output Module codec was actually missing. I changed the default OM template and everything worked fine. Maybe that can help someone having the same error

**Comment by FinnFrotscher** [comment]
yes. i solved it the same way. 
side question. is it possible to render directly to mp4 on mac & ae2020?

**Comment by inlife** [comment]
Unfortunately aerender does not support direct render to mp4 since AE CC 2015, iirc.

**Comment by FinnFrotscher** [comment]
this problem came up again and I do have the default output codec.  
could you share your setup and how you build it? maybe it will lead to a fix.

**Comment by inlife** [comment]
hey @FinnFrotscher 
is the question directed to me? if so, could you please explain in more details what do you mean

**Comment by FinnFrotscher** [comment]
hi, 
the question is both for you and @phlexib, or anyone who has the answer :)

my issue is the following:
- i am running the renderer on a template.aet.
- during startup, after effects throws an error:
```
aerender version 17.0.6x35
PROGRESS: Launching After Effects...
PROGRESS: ...After Effects successfully launched

[ERROR]

"Couldn't find a result file"
```

- i do have the apple pro res codec installed. i both checked the installed software registry, i have rendered with this setup in the past in ae headless mode and since the issue came up, i tested the rendering using the interface and it worked. therefore codec is not the issue.

- i tried the template with and without a render job in the queue, as seen in the screenshot. both yield the same error.
<img width="673" alt="image" src="https://user-images.githubusercontent.com/11148454/81171204-472ca600-8f9c-11ea-8d19-09e16cd3b586.png">

**Comment by FinnFrotscher** [comment]
I am getting this warning when rendering using the interface. maybe its a clue.
<img width="501" alt="image" src="https://user-images.githubusercontent.com/11148454/81172836-506b4200-8f9f-11ea-85b6-ca9ae6dea512.png">

**Comment by FinnFrotscher** [comment]
I am getting the same "existing files" message when  rendering from command line and its the last message before stdend.

``` 
⟩cat run.sh                                                                                                  ...o9g7X53hDR2eT0oW2
#!/bin/bash

/Applications/Adobe\ After\ Effects\ 2020/aerender \
	-project /Users/finnfrotscher/code/cofenster/api.renderer/tmp/Kx9mo9g7X53hDR2eT0oW2/template.aet \
	-comp main \
	-output /Users/finnfrotscher/code/cofenster/api.renderer/tmp/Kx9mo9g7X53hDR2eT0oW2/result.mov \
	-s 0 \
	-r /Users/finnfrotscher/code/cofenster/api.renderer/tmp/Kx9mo9g7X53hDR2eT0oW2/nexrender-Kx9mo9g7X53hDR2eT0oW2-script.jsx




⟩bash run.sh                                                                                                 ...o9g7X53hDR2eT0oW2
aerender version 17.0.6x35
PROGRESS: Launching After Effects...
PROGRESS: ...After Effects successfully launched
Running Script: /Users/finnfrotscher/code/cofenster/api.renderer/tmp/Kx9mo9g7X53hDR2eT0oW2/nexrender-Kx9mo9g7X53hDR2eT0oW2-script.jsx
WARNING:After Effects warning: Skip Existing Files is available only with ONE output module of type Sequence.

```

**Comment by FinnFrotscher** [comment]
`Skip existing files` is off:
<img width="757" alt="image" src="https://user-images.githubusercontent.com/11148454/81179999-bc9f7300-8faa-11ea-862e-4abf6a70c40f.png">

**Comment by aetipps** [comment]
I'm getting the same error.

`> job rendering failed
Error: Couldn't find a result file
    at ChildProcess.<anonymous> (C:\snapshot\nexrender\packages\nexrender-cli\node_modules\@nexrender\core\src\tasks\render.js)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)`

The strange thing is, that there is a file called result.mov in the nexrender directory, which I can playback perfectly fine.

**Comment by phlexib** [comment]
The problem happened to me again when switching from Mac to PC. Fixed By removing everything from the render queue. 
Try that.

**Comment by aetipps** [comment]
Thanks for your suggestion but unfortunately this didn't help.
The project can be rendered without any errors from the commandline using aerender and the GUI. As soon as I user nexrender-cli, the rendering fails. When looking into the nexrender temp directory, I can see all job related files including the result.mov file. Even the log file says that the rendering finished successfully.

**Comment by inlife** [comment]
That sometimes happens, when the after effects returns exit code which is not 0. Could you try to check what is in the log, maybe even tho rendering finishes, there are some errors that cause aerender itself to fail?

**Comment by aetipps** [comment]
Thanks for your help.
There were indeed multiple errors in the log:
`FATAL CreateProcessWithTokenW failed with error: 1314
INFO  Failed to launch IPC broker with medium Integrity level due to error:1314, launching it with default level`

These two had to do with AdobeIPCBroker and could be fixed very easily.

But there is still this entry that I can not get rid of:
`aerender version 17.0.5x16
Using DXGI: Device: "NVIDIA GeForce RTX 2060" has dedicated video RAM (MB): 5980
    name                                    : NVIDIA GeForce RTX 2060
    VendorId                                : 4318
    DeviceId                                : 7944
    SubSysId                                : 543242306
    Revision                                : 161
    DedicatedVideoMemory                    : 6270484480
    DedicatedSystemMemory                   : 0
    SharedSystemMemory                      : 34312624128
    MemoryBudget                            : 5329911808
    AdapterLuid.LowPart                     : 57058
    AdapterLuid.HighPart                    : 0
    Flags                                   : 0
        DoublePrecisionFloatShaderOps           : yes
        ConservativeRasterizationTier           : 3
        CrossNodeSharingTier                    : 0
        ResourceBindingTier                     : 3
        ResourceHeapTier                        : 2
        TiledResourcesTier                      : 3
        NodeIndex                               : 0
        TileBasedRenderer                       : no
        UMA                                     : no
        CacheCoherentUMA                        : no
        feature level                           : 0x00009100
        feature level                           : 0x00009200
        feature level                           : 0x00009300
        feature level                           : 0x0000a000
        feature level                           : 0x0000a100
        feature level                           : 0x0000b000
        feature level                           : 0x0000b100
        feature level                           : 0x0000c000
        feature level                           : 0x0000c100
        MaxSupportedFeatureLevel                : 0x0000c100
        HighestShaderModel                      : 0x60
        WaveOps                                 : yes
        WaveLaneCountMin                        : 32
        WaveLaneCountMax                        : 32
        TotalLaneCount                          : 1920
        ExpandedComputeResourceStates           : yes
        Int64ShaderOps                          : yes
        RootSignature.HighestVersion            : 0x2`

Any help is greatly appreciated.

**Comment by FinnFrotscher** [comment]
i fixed my specific issue by wiggling my after effects default renderer output module and the renderer settings configuration.

**Comment by gen4sp** [comment]
@FinnFrotscher same problem. How exactly have you resolved that?

**Comment by gen4sp** [comment]
I've just solved it by adding an empty file and point to it as output. =/

**Comment by aetipps** [comment]
Fixed my issue by uninstalling and reinstalling After Effects.

**Comment by MrSKYone** [comment]
I, too, am having this issue. Any specific protocol to fix this?
Reinstalling didnt fix the problem :/

**Comment by FinnFrotscher** [comment]
i vaguely remember. you need to build an `Output Module Template` and a `Render Settings Template` at `Edit > Tempaltes > *`
I dont remember the setup i used.

**Comment by Wence-May** [comment]
Hi,
to make an addition,
I found that something wrong with templates can also lead to this error.

At first, I ran into this error.  I was quite sure nothing was wrong with my OM/aerender. After I reset the property "postion" of one of my layers(it had been accidentally changed), the error just gone.

I don't know how, but you may also check the .aep template.

**Comment by shi-ivam** [comment]
> The problem happened to me again when switching from Mac to PC. Fixed By removing everything from the render queue.
> Try that.

This Fixed the issue for me
