### ISSUE TITLE
Umlauts are not displayed correctly after rendering with nexrender

### ISSUE THREAD

**Issue by andre-mgo** [inlife/nexrender#390]
Hi there, I'm trying to use nexrender for rendering automation.
But we encountered a problem if the replacement text contains umlauts (like ö ä ü or ß).
I have created following Json (UTF-8 encoded):
`{
	"template":{
		"src":"file:///home/andre/template",
		"composition":"01_Nach-Corona-Film"
	},
	"actions":{
		"postrender":[{ 
			"module":"@nexrender/action-copy", 
			"output":"/home/andre/test/1_auto_service_s_d_karsten_morsbach.mov"
		}],
		"prerender":[]
	},
	"assets":[{
		"layerName":"company",
		"property":"Source Text",
		"type":"data",
		"value":"Auto-Service-Süd Karsten Morsbach"
	},{
		"layerName":"address",
		"property":"Source Text",
		"type":"data",
		"value":"Am Dördelmannshof 17"
	}]
}`
I also tried with ISO-8859-1 encoding and as unicode escape:
`{
	"template":{
		"src":"file:///home/andre/template",
		"composition":"01_Nach-Corona-Film"
	},
	"actions":{
		"postrender":[{ 
			"module":"@nexrender/action-copy", 
			"output":"/home/andre/test/1_auto_service_s_d_karsten_morsbach.mov"
		}],
		"prerender":[]
	},
	"assets":[{
		"layerName":"company",
		"property":"Source Text",
		"type":"data",
		"value":"Auto-Service-S\u00FCd Karsten Morsbach"
	},{
		"layerName":"address",
		"property":"Source Text",
		"type":"data",
		"value":"Am D\u00F6rdelmannshof 17"
	}]
}`

But none of them did render the correct umlauts.

Environment information:
I use nexrender-cli (prebuild binary) version 1.15.1 on mac with Adobe AfterEffects 2019.
iMacPro(2017) macOS Mojave Version 10.14.6

Expected behavior:
It should render the correct umlauts (äöüß)

Here a screenshot from the rendered vido with broken umlauts:
https://www.dropbox.com/s/2ta7lfbu56t7drk/thumbnail_image001.png?dl=0

**Comment by inlife** [comment]
Please try testing this same issue with `v1.16.1` or later, it should be fixed.

**Comment by andre-mgo** [comment]
Hi, we tried with v1.16.1 but unfortunately still the same result with broken umlauts.

**Comment by inlife** [comment]
Could you also check the version of the `commadLineRenderer.jsx` file in the top comment.
It is located in a folder resembling this path: `After Effects/Support Files/Scripts/Startup/`

It should be: `(nexrender-patch-v1.0.2)`
If it is not, the update was not installed properly.

**Comment by andre-mgo** [comment]
Hi, sorry for the late response. 
The file does not contain any version number.
Should be delete it?

**Comment by inlife** [comment]
Make sure you are looking at the same file nexrender does. Check if nexrender uses same installation folder for after effects you were viewing.

The file **MUST** have this version, otherwise, it means nexrender was not even installed properly.

**Comment by andre-mgo** [comment]
Hi, in the file
/Applications/Adobe After Effects CC 2019/Scripts/Startup/commandLineRenderer.jsx
the first line is following entry:
// Command line renderer for After Effects. (nexrender-patch-v1.0.2)
But unfortunately umlauts still do not work.

**Comment by andre-mgo** [comment]
Perhaps as a hint: the create script.jsx has the wrong characters inside.
So from json file utf8: 
`{ "layerName":"company", "property":"Source Text", "type":"data", "value":"Test Company öäü" }`
it creates jsx:
`(function() {
    nexrender.selectLayersByName(null, 'company', function(layer) {

        var parts = ["Source Text"];
        var value = { "value": 'Test Company ���' }
        
        nexrender.changeValueForKeypath(layer, parts, value);

        return true;
    });
})();`

**Comment by inlife** [comment]
Oh yea, that looks different. For other users it was looking properly in script.js, but for you it is wrong here. Please check the encoding of the generated script.js, is it also utf-8?

**Comment by andre-mgo** [comment]
Hi, I apologize for the inconvenience. You are right, config file was generated not in UTF-8, now it is working. Thanks a lot.
